services:
  morieru-dl:
    image: morieru-dl
    container_name: morieru-dl
    hostname: morieru-dl
    build:
      context: ./
      args:
        UID: 1000
        GID: 1000
        USERNAME: app
        GROUPNAME: app
      dockerfile: Dockerfile
    volumes:
      - /share/morierus:/home/app/morierus
      - ./share:/home/app/share
